// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoG3.Infrastructure.Persistence;

#nullable disable

namespace ProyectoG3.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProyectoG3.Domain.Entities.Comercio", b =>
                {
                    b.Property<int>("IdComercio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComercio"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoDeComercio")
                        .HasColumnType("int");

                    b.Property<int>("TipoIdentificacion")
                        .HasColumnType("int");

                    b.HasKey("IdComercio");

                    b.ToTable("Comercios");
                });

            modelBuilder.Entity("ProyectoG3.Domain.Entities.ConfiguracionComercio", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<int>("Comision")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<int>("TipoConfiguracion")
                        .HasColumnType("int");

                    b.HasKey("IdConfiguracion");

                    b.HasIndex("IdComercio")
                        .IsUnique();

                    b.ToTable("ConfiguracionComercioG3");
                });

            modelBuilder.Entity("ProyectoG3.Domain.Entities.ReporteMensual", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<int>("CantidadDeCajas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadDeSINPES")
                        .HasColumnType("int");

                    b.Property<int?>("ComercioIdComercio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDelReporte")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotalComision")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontoTotalRecaudado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdReporte");

                    b.HasIndex("ComercioIdComercio");

                    b.ToTable("ReportesMensuales");
                });

            modelBuilder.Entity("ProyectoG3.Domain.Entities.Sinpe", b =>
                {
                    b.Property<int>("IdSinpe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSinpe"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreOrigen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TelefonoDestinatario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TelefonoOrigen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdSinpe");

                    b.ToTable("Sinpes");
                });

            modelBuilder.Entity("ProyectoG3.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdNetUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUsuario");

                    b.ToTable("UsuariosG3");
                });

            modelBuilder.Entity("ProyectoG3.Models.BitacoraEvento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("longtext");

                    b.Property<string>("DatosPosteriores")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionDeEvento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaDeEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TablaDeEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDeEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdEvento");

                    b.ToTable("BitacoraEventos");
                });

            modelBuilder.Entity("ProyectoG3.Models.Caja", b =>
                {
                    b.Property<int>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCaja"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoSINPE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCaja");

                    b.HasIndex("IdComercio");

                    b.ToTable("CAJAS");
                });

            modelBuilder.Entity("ProyectoG3.Domain.Entities.ConfiguracionComercio", b =>
                {
                    b.HasOne("ProyectoG3.Domain.Entities.Comercio", "Comercio")
                        .WithOne("Configuracion")
                        .HasForeignKey("ProyectoG3.Domain.Entities.ConfiguracionComercio", "IdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("ProyectoG3.Domain.Entities.ReporteMensual", b =>
                {
                    b.HasOne("ProyectoG3.Domain.Entities.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioIdComercio");

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("ProyectoG3.Models.Caja", b =>
                {
                    b.HasOne("ProyectoG3.Domain.Entities.Comercio", "Comercio")
                        .WithMany("CAJAS")
                        .HasForeignKey("IdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("ProyectoG3.Domain.Entities.Comercio", b =>
                {
                    b.Navigation("CAJAS");

                    b.Navigation("Configuracion");
                });
#pragma warning restore 612, 618
        }
    }
}
